### ISSUE TITLE
ROS Simulation - Github BED Workshop finalize 

### ISSUE THREAD

**Issue by diwalipathak** [5G-ERA/middleware#61] opened 2022-12-01 09:52 UTC
**Describe the bug**
In BED-Workshop, Step 3: Performance Image Functionality 
1. ROS-Simulation, launch the telenot pod is not working properly 
2. Measure performance of ROS2 system and topologies is also not working properly. 

##Needs urgent work
![ROS-SIMULATION](https://user-images.githubusercontent.com/93341077/205025985-3cc7a651-98c5-41c9-a05d-17356a9ab4a2.jpg)

**Comment by Artonus** [comment] 2022-12-01 10:09
@diwalipathak, I guess that this issue is a duplicate of #62? If it is, then please close this one.

**Comment by diwalipathak** [comment] 2022-12-01 10:11
Closed, duplicate of #62

**Closed** 2022-12-01 10:11 UTC
Labels: documentation
